include required(file("/app/storage.conf"))

_client_credentials_auth_config {
  type = "client-credentials"
  well-known-config-url = ${?SPLICE_APP_SYNC_OPERATOR_LEDGER_API_AUTH_URL}
  client-id = ${?SPLICE_APP_SYNC_OPERATOR_LEDGER_API_AUTH_CLIENT_ID}
  client-secret = ${?SPLICE_APP_SYNC_OPERATOR_LEDGER_API_AUTH_CLIENT_SECRET}
  audience = ${SPLICE_APP_SYNC_OPERATOR_LEDGER_API_AUTH_AUDIENCE}
  scope = ${?SPLICE_APP_SYNC_OPERATOR_LEDGER_API_AUTH_SCOPE}
}

_sync_operator_participant_client {
  admin-api = {
    address = ${SPLICE_APP_SYNC_OPERATOR_PARTICIPANT_ADDRESS}
    port = 5002
  }
  ledger-api.client-config = {
    address = ${SPLICE_APP_SYNC_OPERATOR_PARTICIPANT_ADDRESS}
    port = 5001
  }
  ledger-api.auth-config = ${_client_credentials_auth_config}
}

canton {
  sync-operator-apps {
    sync-operator {
      storage = ${_storage}
      admin-api = {
        address = "0.0.0.0"
        port = 5016
      }
      participant-client = ${_sync_operator_participant_client}
      scan-client.admin-api.url = ${SPLICE_APP_SYNC_OPERATOR_SCAN_URL}
      operator-user = ${SPLICE_APP_SYNC_OPERATOR_LEDGER_API_AUTH_USER_NAME}
      synchronizer-nodes.current.sequencer.admin-api {
        address = ${SPLICE_APP_SYNC_OPERATOR_SEQUENCER_ADDRESS}
        port = 5009
      }
    }
  }
}
