canton.remote-participants.app-operator.token = ${APP_PROVIDER_VALIDATOR_USER_TOKEN}
canton.remote-participants.app-operator-2.token = ${APP_PROVIDER_VALIDATOR_USER_TOKEN}
canton.remote-participants.app-operator-3.token = ${APP_PROVIDER_VALIDATOR_USER_TOKEN}
canton.remote-participants.app-operator-4.token = ${APP_PROVIDER_VALIDATOR_USER_TOKEN}
canton.remote-participants.app-operator-5.token = ${APP_PROVIDER_VALIDATOR_USER_TOKEN}
