# Remote references to nodes 2 to 5 of the four-node app-synchronizer (-B), and to the
# participants of the orgs that run nodes 1 to 5.
canton.remote-sequencers.app-sequencer-2 {
  public-api {
    address = canton
    port = 5218
  }

  admin-api {
    address = canton
    port = 5219
  }
}

canton.remote-mediators.app-mediator-2 {

  admin-api {
    address = canton
    port = 5217
  }
}

canton.remote-sequencers.app-sequencer-3 {
  public-api {
    address = canton
    port = 5318
  }

  admin-api {
    address = canton
    port = 5319
  }
}

canton.remote-mediators.app-mediator-3 {

  admin-api {
    address = canton
    port = 5317
  }
}

canton.remote-sequencers.app-sequencer-4 {
  public-api {
    address = canton
    port = 5418
  }

  admin-api {
    address = canton
    port = 5419
  }
}

canton.remote-mediators.app-mediator-4 {

  admin-api {
    address = canton
    port = 5417
  }
}

canton.remote-sequencers.app-sequencer-5 {
  public-api {
    address = canton
    port = 5518
  }

  admin-api {
    address = canton
    port = 5519
  }
}

canton.remote-mediators.app-mediator-5 {

  admin-api {
    address = canton
    port = 5517
  }
}

canton.remote-participants.app-operator {
  ledger-api {
    address = canton
    port = 6001
  }

  admin-api {
    address = canton
    port = 6002
  }
}

canton.remote-participants.app-operator-2 {
  ledger-api {
    address = canton
    port = 6201
  }

  admin-api {
    address = canton
    port = 6202
  }
}

canton.remote-participants.app-operator-3 {
  ledger-api {
    address = canton
    port = 6301
  }

  admin-api {
    address = canton
    port = 6302
  }
}

canton.remote-participants.app-operator-4 {
  ledger-api {
    address = canton
    port = 6401
  }

  admin-api {
    address = canton
    port = 6402
  }
}

canton.remote-participants.app-operator-5 {
  ledger-api {
    address = canton
    port = 6501
  }

  admin-api {
    address = canton
    port = 6502
  }
}
