{
 "title": "Sync Operator",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(splice_trigger_iterations_total{node_type=\"syncoperator\"},namespace)"
    }
   },
   {
    "name": "operator",
    "label": "Sync operator",
    "query": {
     "query": "label_values(splice_trigger_iterations_total{namespace=\"$namespace\", node_type=\"syncoperator\"},node_name)"
    }
   },
   {
    "name": "job",
    "label": "Sequencer job",
    "query": {
     "query": "label_values(daml_sequencer_traffic_control_extra_traffic_purchased{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "node",
    "label": "Sequencer node",
    "query": {
     "query": "label_values(daml_sequencer_traffic_control_extra_traffic_purchased{namespace=\"$namespace\", job=\"$job\"},node)"
    }
   },
   {
    "name": "member",
    "label": "Member",
    "query": {
     "query": "label_values(daml_sequencer_traffic_control_extra_traffic_purchased{namespace=\"$namespace\", job=\"$job\", node=~\"$node\"},member)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Traffic position on the dedicated synchronizer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Traffic Per Participant",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(member) (daml_sequencer_traffic_control_extra_traffic_purchased{namespace=\"$namespace\", job=\"$job\", node=~\"$node\", member=~\"$member\", member=~\"PAR::.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(member) (daml_sequencer_traffic_control_extra_traffic_consumed{namespace=\"$namespace\", job=\"$job\", node=~\"$node\", member=~\"$member\", member=~\"PAR::.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extra Traffic Purchased And Consumed By Participant",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(member) (daml_sequencer_traffic_control_extra_traffic_purchased{namespace=\"$namespace\", job=\"$job\", node=~\"$node\", member=~\"$member\", member=~\"PAR::.*\"})",
     "legendFormat": "{{member}} purchased"
    },
    {
     "expr": "sum by(member) (daml_sequencer_traffic_control_extra_traffic_consumed{namespace=\"$namespace\", job=\"$job\", node=~\"$node\", member=~\"$member\", member=~\"PAR::.*\"})",
     "legendFormat": "{{member}} consumed"
    }
   ]
  },
  {
   "title": "Extra Traffic Available By Participant",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expression": "$extra_traffic_purchased - $extra_traffic_consumed",
     "type": "math"
    }
   ]
  },
  {
   "title": "Traffic Purchased over the last 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (member) (delta(daml_sequencer_traffic_control_extra_traffic_purchased{namespace=\"$namespace\", job=\"$job\", node=~\"$node\", member=~\"$member\", member=~\"PAR::.*\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Tier Traffic Available By Participant/Mediator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(member) (daml_sequencer_traffic_control_base_traffic_remainder{namespace=\"$namespace\", job=\"$job\", node=~\"$node\", member=~\"$member\", member=~\"(PAR|MED)::.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic consumption on the dedicated synchronizer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "Delivered Event Traffic Rate By Event Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(daml_sequencer_traffic_control_event_delivered_cost_total{namespace=\"$namespace\", job=\"$job\", node=~\"$node\", member=~\"$member\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected Event Traffic Rate By Event Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(daml_sequencer_traffic_control_event_rejected_cost_total{namespace=\"$namespace\", job=\"$job\", node=~\"$node\", member=~\"$member\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconciliation by the sync operator app",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }
  },
  {
   "title": "Reconcile Latency (p95)",
   "type": "timeseries",
   "description": "The time it took to perform an iteration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(splice_trigger_latency_duration_seconds{namespace=\"$namespace\", node_type=\"syncoperator\", node_name=~\"$operator\", trigger_name=\"ReconcileDedicatedSequencerTrafficTrigger\"}[$__rate_interval]))",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "stat",
   "description": "The rate at which the trigger(s) are failing with retryable errors",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(splice_retries_failures{namespace=\"$namespace\", node_type=\"syncoperator\", node_name=~\"$operator\", error_kind=\"transient\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "The rate at which trigger(s) are failing with fatal/non-retryable errors",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(splice_retries_failures{namespace=\"$namespace\", node_type=\"syncoperator\", node_name=~\"$operator\", error_kind=\"fatal\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Completed Tasks By Outcome",
   "type": "timeseries",
   "description": "How busy triggers are within a certain time window",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(trigger_name, node_name, outcome) (rate(splice_trigger_completed_total{namespace=\"$namespace\", node_type=\"syncoperator\", node_name=~\"$operator\"}[$__rate_interval]))",
     "legendFormat": "{{node_name}} {{trigger_name}} {{outcome}}"
    }
   ]
  },
  {
   "title": "Trigger Attempts By Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum by(trigger_name, statusCode) (rate(splice_trigger_attempted_total{namespace=\"$namespace\", node_type=\"syncoperator\", node_name=~\"$operator\"}[$__rate_interval]))",
     "legendFormat": "{{trigger_name}} {{statusCode}}"
    }
   ]
  }
 ]
}