canton.sync-operator-apps.sync-operator {
  participant-client.ledger-api.auth-config = {
    type = "self-signed"
    user = ${canton.validator-apps.app-provider-validator_backend.app-instances.syncOperator.service-user}
    audience = ${AUTH_APP_PROVIDER_AUDIENCE}
    secret = "unsafe"
  }
  auth = {
    algorithm = "hs-256-unsafe"
    audience = ${AUTH_APP_PROVIDER_AUDIENCE}
    secret = "unsafe"
  }
}
