canton.validator-apps.app-provider-validator_backend.app-instances.syncOperator {
  service-user = "sync-operator"
  dars = []
}

canton.sync-operator-apps.sync-operator {
  storage = ${_storage}
  storage.config.properties.databaseName = sync-operator
  storage.config.properties.currentSchema = sync-operator
  admin-api {
    address = "0.0.0.0"
    port = 3${SYNC_OPERATOR_ADMIN_API_PORT_SUFFIX}
  }
  operator-user = ${canton.validator-apps.app-provider-validator_backend.app-instances.syncOperator.service-user}
  participant-client = ${canton.validator-apps.app-provider-validator_backend.participant-client}
  scan-client.admin-api.url = ${?SPLICE_APP_VALIDATOR_SCAN_ADDRESS}
  sequencer.admin-api {
    address = canton
    port = 5019
  }
}
