# The org participants accept the same tokens as the app-provider participant.
_app_operator_auth {
  auth-services = [{
    type = unsafe-jwt-hmac-256
    target-audience = ${AUTH_APP_PROVIDER_AUDIENCE}
    secret = "unsafe"
  }]

  user-management-service.additional-admin-user-id = ${AUTH_APP_PROVIDER_VALIDATOR_USER_NAME}
}

canton.participants.app-operator.ledger-api = ${_app_operator_auth}
canton.participants.app-operator-2.ledger-api = ${_app_operator_auth}
canton.participants.app-operator-3.ledger-api = ${_app_operator_auth}
canton.participants.app-operator-4.ledger-api = ${_app_operator_auth}
canton.participants.app-operator-5.ledger-api = ${_app_operator_auth}
